#!/bin/bash
# codex-fallback setup script
# Syncs Claude Code project context into Codex CLI format
# Run this in any project directory before switching to Codex

set -e

PROJECT_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || pwd)
CODEX_DIR="$HOME/.codex"

echo "codex-fallback: syncing Claude context → Codex"
echo "project: $PROJECT_ROOT"
echo ""

# ── 1. Find Claude project context ──────────────────────────
CLAUDE_MD=""
MEMORY_CONTENT=""

# Check for project CLAUDE.md
if [ -f "$PROJECT_ROOT/CLAUDE.md" ]; then
    CLAUDE_MD=$(cat "$PROJECT_ROOT/CLAUDE.md")
    echo "  found: CLAUDE.md (project)"
fi

# Check for global CLAUDE.md
if [ -f "$HOME/.claude/CLAUDE.md" ]; then
    if [ -n "$CLAUDE_MD" ]; then
        CLAUDE_MD="$CLAUDE_MD

---

$(cat "$HOME/.claude/CLAUDE.md")"
    else
        CLAUDE_MD=$(cat "$HOME/.claude/CLAUDE.md")
    fi
    echo "  found: CLAUDE.md (global)"
fi

# Find memory files for this project
SLUG=$(echo "$PROJECT_ROOT" | sed 's|/|-|g' | sed 's|^-||')
MEMORY_DIR="$HOME/.claude/projects/$SLUG/memory"
if [ -d "$MEMORY_DIR" ]; then
    for f in "$MEMORY_DIR"/*.md; do
        [ -f "$f" ] || continue
        MEMORY_CONTENT="$MEMORY_CONTENT

--- $(basename "$f") ---
$(cat "$f")"
    done
    echo "  found: memory files ($(ls "$MEMORY_DIR"/*.md 2>/dev/null | wc -l | tr -d ' ') files)"
fi

# Also check the broader pattern Claude uses
for PDIR in "$HOME/.claude/projects/"*"$( basename "$PROJECT_ROOT")"*/memory; do
    [ -d "$PDIR" ] || continue
    for f in "$PDIR"/*.md; do
        [ -f "$f" ] || continue
        MEMORY_CONTENT="$MEMORY_CONTENT

--- $(basename "$f") ---
$(cat "$f")"
    done
    echo "  found: memory files in $PDIR"
done

# ── 2. Gather project structure ─────────────────────────────
STRUCTURE=$(find "$PROJECT_ROOT" -maxdepth 2 -type f \
    -not -path '*/node_modules/*' \
    -not -path '*/.git/*' \
    -not -path '*/venv/*' \
    -not -path '*/__pycache__/*' \
    -not -path '*/.next/*' \
    -not -path '*/dist/*' \
    -not -name '*.pyc' \
    -not -name '.DS_Store' \
    2>/dev/null | sort | head -80)

# ── 3. Get git context ──────────────────────────────────────
GIT_CONTEXT=""
if git rev-parse --git-dir > /dev/null 2>&1; then
    BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")
    RECENT_COMMITS=$(git log --oneline -10 2>/dev/null || echo "no commits")
    GIT_STATUS=$(git status --short 2>/dev/null | head -20)
    GIT_CONTEXT="Branch: $BRANCH

Recent commits:
$RECENT_COMMITS

Working tree:
$GIT_STATUS"
    echo "  found: git context (branch: $BRANCH)"
fi

# ── 4. Get package/project info ─────────────────────────────
PKG_INFO=""
[ -f "$PROJECT_ROOT/package.json" ] && PKG_INFO="$PKG_INFO
$(cat "$PROJECT_ROOT/package.json")" && echo "  found: package.json"
[ -f "$PROJECT_ROOT/pyproject.toml" ] && PKG_INFO="$PKG_INFO
$(head -40 "$PROJECT_ROOT/pyproject.toml")" && echo "  found: pyproject.toml"
[ -f "$PROJECT_ROOT/Cargo.toml" ] && PKG_INFO="$PKG_INFO
$(head -40 "$PROJECT_ROOT/Cargo.toml")" && echo "  found: Cargo.toml"
[ -f "$PROJECT_ROOT/go.mod" ] && PKG_INFO="$PKG_INFO
$(cat "$PROJECT_ROOT/go.mod")" && echo "  found: go.mod"

# ── 5. Write AGENTS.md in the project root ──────────────────
AGENTS_FILE="$PROJECT_ROOT/AGENTS.md"

cat > "$AGENTS_FILE" << 'HEREDOC_TOP'
# Project Instructions

> Auto-generated by codex-fallback from Claude Code context.
> Re-run `setup.sh` to refresh after Claude sessions.

HEREDOC_TOP

if [ -n "$CLAUDE_MD" ]; then
    cat >> "$AGENTS_FILE" << HEREDOC_CLAUDE
## Project Conventions (from CLAUDE.md)

$CLAUDE_MD

HEREDOC_CLAUDE
fi

if [ -n "$MEMORY_CONTENT" ]; then
    cat >> "$AGENTS_FILE" << HEREDOC_MEMORY
## Context & Decisions (from Claude Memory)

$MEMORY_CONTENT

HEREDOC_MEMORY
fi

if [ -n "$GIT_CONTEXT" ]; then
    cat >> "$AGENTS_FILE" << HEREDOC_GIT
## Current State

$GIT_CONTEXT

HEREDOC_GIT
fi

cat >> "$AGENTS_FILE" << HEREDOC_RULES
## Working Rules

- Follow the patterns already in the codebase. Match existing code style exactly.
- Do not add unnecessary comments or docstrings to code you didn't change.
- Do not refactor code you weren't asked to change.
- When creating files, check existing files in the same directory for conventions.
- When creating markdown files, match the formatting conventions of existing files in the same directory.
- Be concise in output. Do the work, confirm briefly, move on.
- Do NOT read or execute any files under ~/.claude/ or .claude/skills/. Those are for a different tool.
HEREDOC_RULES

echo ""
echo "  wrote: $AGENTS_FILE ($(wc -l < "$AGENTS_FILE" | tr -d ' ') lines)"

# ── 6. Trust the project in Codex config ────────────────────
if [ -f "$CODEX_DIR/config.toml" ]; then
    if ! grep -q "\"$PROJECT_ROOT\"" "$CODEX_DIR/config.toml" 2>/dev/null; then
        echo "" >> "$CODEX_DIR/config.toml"
        echo "[projects.\"$PROJECT_ROOT\"]" >> "$CODEX_DIR/config.toml"
        echo 'trust_level = "trusted"' >> "$CODEX_DIR/config.toml"
        echo "  added: project trust in codex config"
    else
        echo "  exists: project already trusted in codex config"
    fi
fi

echo ""
echo "done. run 'codex' in this directory and it'll have your Claude context."
echo ""
echo "tip: add AGENTS.md to .gitignore if you don't want it committed:"
echo "  echo 'AGENTS.md' >> .gitignore"
